refactor(sg): added anti-user-gateway
skyra-project/skyra pull request #1077
Opened 2020-07-14 17:30 UTC by kyranet

2020-07-14 17:37 UTC, favna requested changes

2020-07-14 17:37 UTC, Favna commented on src/lib/util/AntiUserGateway.ts
> +		// @ts-ignore
Add a short description as to why there is a ts-ignore then eslint won't complain either.

2020-07-14 17:37 UTC, Favna commented on src/lib/util/AntiUserGateway.ts
> +		// @ts-ignore
Add a short description as to why there is a ts-ignore then eslint won't complain either.

2020-07-14 17:37 UTC, Favna commented on src/lib/util/AntiUserGateway.ts
> +// @ts-ignore
Add a short description as to why there is a ts-ignore then eslint won't complain either.

2020-07-14 18:12 UTC, favna approved these changes

2020-07-14 18:28 UTC, merged

2020-08-16 09:50 UTC, kyranet commented
This pull request needs to be reverted with our latest changes to our fork.