feat(Analytics): Twitch analytics
skyra-project/skyra pull request #1088
Opened 2020-07-15 07:26 UTC by QuantumlyTangled

Closes #1087

2020-07-15 09:34 UTC, kyranet requested changes

2020-07-15 09:34 UTC, kyranet commented on src/routes/twitch/twitchStreamChange.ts
> +	public async post(request: ApiRequest, response: ApiResponse) {
```suggestion
	public post(request: ApiRequest, response: ApiResponse) {
```

2020-07-15 09:34 UTC, kyranet commented on src/routes/twitch/twitchStreamChange.ts
>  			this.client.emit(Events.TwitchStreamOnline, data[0], response);
```suggestion
		if (lengthStatus) {
			this.client.emit(Events.TwitchStreamHookedAnalytics, AnalyticsSchema.TwitchStreamStatus.Online);
			this.client.emit(Events.TwitchStreamOffline, { id }, response);
		} else {
			this.client.emit(Events.TwitchStreamHookedAnalytics, AnalyticsSchema.TwitchStreamStatus.Offline);
			this.client.emit(Events.TwitchStreamOnline, data[0], response);
```

2020-07-15 23:26 UTC, kyranet requested changes

2020-07-15 23:26 UTC, kyranet commented on src/events/analytics/analyticsSync.ts
> +		const twitchSubscriptionCount = await dbSet.twitchStreamSubscriptions.count();
```suggestion
		const [economyHealth, twitchSubscriptionCount] = await Promise.all([
			this.fetchEconomyHealth(dbSet),
			dbSet.twitchStreamSubscriptions.count()
		]);
```

2020-07-15 23:29 UTC, kyranet approved these changes

2020-07-16 07:21 UTC, favna approved these changes

2020-07-16 07:32 UTC, merged