chore(EditorConfig): Add parameters for the other used file types
skyra-project/skyra pull request #1101
Opened 2020-07-16 17:17 UTC by QuantumlyTangled

2020-07-16 17:43 UTC, favna submitted a review, later dismissed

2020-07-18 14:39 UTC, kyranet requested changes

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +		...evolutionsData
```suggestion
			...evolutionsData
```

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +		...evolutionsData
```suggestion
			...evolutionsData
```

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +	...ability
```suggestion
		...ability
```

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +	...learnsetLevelupMove
```suggestion
		...learnsetLevelupMove
```

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +	...learnset
```suggestion
		...learnset
```

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +	...moves
```suggestion
		...moves
```

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +	...typeEntry
```suggestion
		...typeEntry
```

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +	...typeEntry
```suggestion
		...typeEntry
```

2020-07-18 14:39 UTC, kyranet commented on src/lib/util/Pokemon.ts
> +	...typesMatchups
```suggestion
		...typesMatchups
```

2020-07-18 14:49 UTC, favna submitted a review, later dismissed

2020-07-18 14:50 UTC, kyranet submitted a review, later dismissed

2020-07-18 14:59 UTC, favna approved these changes

2020-07-18 15:11 UTC, kyranet approved these changes

2020-07-18 15:11 UTC, merged