refactor(api): change auth to be cookie-based
skyra-project/skyra pull request #1102
Opened 2020-07-16 18:09 UTC by kyranet

Pending for skyra.pw to be updated with the new code.

2020-07-16 19:40 UTC, Quantumlyy submitted a review, later dismissed

2020-07-16 22:13 UTC, Favna commented
Dashboard is ready, master has been updated as of https://github.com/skyra-project/skyra.pw/commit/03cd4a64925e953569d9c2dbdb89d4c9ad2a06eb.

2020-07-17 06:43 UTC, favna requested changes

2020-07-17 06:43 UTC, Favna commented on src/middlewares/authenticated.ts
> +	public constructor(store: MiddlewareStore, file: string[], directory: string) {
Middleware extends piece doesn't it? If so ApplyOptions please

2020-07-17 06:43 UTC, Favna commented on src/middlewares/cookies.ts
> +		super(store, file, directory, { priority: 30 });
Ditto

2020-07-17 06:44 UTC, Favna commented
There's some todo's left for the dashboard

- logout should call logout endpoint rather than only pruning locally

- checking that 403's in sync user go to logout

2020-07-17 18:43 UTC, favna approved these changes

2020-07-17 18:48 UTC, Quantumlyy approved these changes

2020-07-17 18:48 UTC, merged