feat: setup docker config for saelem w/ redis
skyra-project/skyra pull request #1188
Opened 2020-08-08 14:31 UTC by Favna

Pending merge and subsequent release of https://github.com/skyra-project/saelem/pull/6

TODO:
- [ ] bump Saelem devdependency﻿

2020-08-08 15:04 UTC, Rexogamer requested changes

2020-08-08 15:04 UTC, Rexogamer commented on docker/README.md
> +	note: ***do not edit the SAELEM_REDIS_PORT***
```suggestion
	Note: ***DO NOT edit the SAELEM_REDIS_PORT***
```

2020-08-08 15:04 UTC, Rexogamer commented on docker/README.md
> +    1. Copy the [`redis.conf`] file in [`configs`] directory and rename the copy to [`redis.local.conf`]
```suggestion
    1. Copy the [`redis.conf`] file in the [`configs`] directory and rename the new file to [`redis.local.conf`]
```

2020-08-08 15:04 UTC, Rexogamer commented on docker/README.md
> +	note: ***do not edit the port!***
```suggestion
	Note: ***DO NOT edit the port!***
```

2020-08-08 15:04 UTC, Rexogamer commented on docker/README.md
> +	2. Fill in a password as desired. This should match the values in [`.env.local`]
```suggestion
	2. Fill in the password as desired. This should match the values in [`.env.local`]  
```

2020-08-08 15:08 UTC, Rexogamer submitted a review, later dismissed

2020-08-08 16:06 UTC, Stitch07 submitted a review, later dismissed

2020-08-13 19:30 UTC, kyranet approved these changes

2020-08-13 19:31 UTC, merged