refactor: commit linting
skyra-project/skyra pull request #1191
Opened 2020-08-09 18:28 UTC by QuantumlyTangled

2020-08-10 13:03 UTC, favna requested changes
Also please modify the format checking job to use prettier instead of eclint

2020-08-10 13:03 UTC, favna commented on .yarnclean
> +*.md
```suggestion
*.md

```
newline EOF

2020-08-10 13:03 UTC, favna commented on .vscode/settings.json
>  	},
Remove this as well as the TypeScript part if we're moving to Prettier

2020-08-10 13:03 UTC, favna commented on .yarnclean
> -js-yaml/lib/
Was stuff failing when this was getting removed? same for the core-js/web removal.

2020-08-10 13:03 UTC, favna commented on package.json
> +			"post-commit": "git update-index --again"
why this post-commit line?

2020-08-10 13:03 UTC, favna commented on package.json
> +		"*.{js,ts,mjs,yml,yaml,md,rmd,mkd,mkdn,mdwn,mdown,markdown,litcoffee,ps1}": "eclint fix src tests scripts docker .github"
```suggestion
```

Prettier also does markdown and yaml and we don't have "rmd", "mdwn", "mdown" or "litcoffee" files. Also as stated in other feedback, eclint will be removed.

2020-08-10 13:03 UTC, favna commented on package.json
> +		"*.ts": [
```suggestion
		"*.{mjs,js,ts}": [
```
Should run eslint on .mjs, .js and .ts files

2020-08-10 13:03 UTC, favna commented on package.json
> +			"prettier --write",
```suggestion
```

covered by eslint plugin prettier

2020-08-10 13:03 UTC, favna commented on package.json
> +		"eclint": "^2.8.1",
```suggestion
```

If we're using prettier for formatting then we shouldn't also use editorconfig as they are bound to conflict at some point

2020-08-10 13:03 UTC, favna commented on .eslintrc.json
> +	"extends": ["@skyra", "plugin:prettier/recommended"],
Please follow these steps:

1. Remove this plugin extends
2. Run prettier with `yarn format`
3. Run eslint *without* autofix
4. Ensure any other rules that pop up get disabled.

I'm saying this because the plugin doesn't naturally disable ESLint rules (see https://github.com/prettier/eslint-plugin-prettier#recommended-configuration) and Skyra's eslint config is pretty strict on formatting.

2020-08-10 13:09 UTC, favna requested changes

2020-08-10 13:09 UTC, Favna commented on package.json
> +			"pre-commit": "yarn lint-staged",
```suggestion
			"pre-commit": "yarn pretty-quick --staged && yarn lint-staged",
```

2020-08-10 21:42 UTC, kyranet commented on .eslintrc.json
> +	"extends": ["@skyra", "plugin:prettier/recommended"],
Skyra's eslint config uses TS's rules, adding `prettier/@typescript-eslint` before this one will disable the style keys, then `plugin:prettier/recommended` would set them without conflicts.

2020-08-10 22:45 UTC, Favna commented on .eslintrc.json
> +	"extends": ["@skyra", "plugin:prettier/recommended"],
Apparently the plugin includes eslint-config-prettier https://yarnpkg.com/package/eslint-config-prettier

2020-08-11 05:29 UTC, QuantumlyTangled commented on .yarnclean
> -js-yaml/lib/
Yes, if I recall correctly it was Husky and prettier.

2020-08-11 05:31 UTC, QuantumlyTangled commented on package.json
> +			"post-commit": "git update-index --again"
When reading the Lint-staged documentation they recommend to add this for people who commit using IDEs for instance VSC or WebStorm (it mostly happens on JetBrains products though).

2020-08-11 05:34 UTC, QuantumlyTangled commented on .eslintrc.json
> +	"extends": ["@skyra", "plugin:prettier/recommended"],
What would be the final consensus on this? Most of the PR was based on how @favna did this in Outflux.

2020-08-11 06:15 UTC, Favna commented on .eslintrc.json
> +	"extends": ["@skyra", "plugin:prettier/recommended"],
Ignore this comment is the final consensus

2020-08-12 20:55 UTC, Favna commented on package.json
> +			"post-commit": "git update-index --again"
Did you also read the first line of that section?

> Update: The latest version of JetBrains IDEs now support running hooks as you would expect.

And that's been there for the past 2 years: https://github.com/okonet/lint-staged/commit/352ab8c7aed47f1bc2f22be45a6b6877c025f88b

2020-08-12 22:15 UTC, favna approved these changes
Coveralls change is within acceptable parameters

2020-08-12 22:15 UTC, merged