feat: store users gi character data
skyra-project/skyra pull request #1214
Opened 2020-08-17 04:36 UTC by QuantumlyTangled

Closes #1080

2020-08-17 08:24 UTC, favna requested changes
Needs a migration to create the new table

2020-08-17 08:27 UTC, favna requested changes

2020-08-17 08:27 UTC, Favna commented on src/lib/orm/entities/UserGameIntegrationsEntity.ts
> +@Entity('user_game_integrations', { schema: 'public' })
"integration" singular please. It's the standard we follow. Each row is a single integration for that user.

2020-08-17 08:31 UTC, kyranet requested changes

2020-08-17 08:31 UTC, kyranet commented on src/lib/orm/repositories/UserRepository.ts
> +		const user = await this.ensure(id, { ...options, relations: ['profile'] });
```suggestion
		const user = await this.ensure(id, { ...options, relations: ['gi'] });
```

2020-08-17 08:36 UTC, favna requested changes
Also I think it should be a OneToMany relation. Every One user has Many game integration entries, and each entry can be i.e. a saved FFXIV character or a saved Clash of Clans character etc.

I.e. I was thinking a data structure like this

| user_id | command_name | extra_data                                                                      |
|---------|--------------|---------------------------------------------------------------------------------|
| 123465  | ffxiv        | {{ "type": "character", "server": "Ardevon", "characterName": "Laytlan" }}      |
| 789456  | ffxiv        | {{ "type": "character", "server": "Aether", "characterName": "Dante Esparda" }} |
| 789456  | clashofclans | {{ "type": "player", "tag": "#8GQPJG2CL" }}                                     |
| 123456  | clashofclans | {{ "type": "clan", "name": "Hog Raiders Swe" }}                                 |

Then the database query for saved stuff can be 

```sql
SELECT extra_data
FROM user_game_integration
WHERE user_id = %1
  AND command_name = %2

PARAMETERS [message.author.id, message.command.name]
```

---

On that note, also actually populate the `UserGameIntegrationsEntity.ts` with some columns because right now it's a columnless table pretty much.

2020-08-22 08:26 UTC, kyranet requested changes

2020-08-22 08:26 UTC, kyranet commented on src/lib/orm/entities/UserEntity.ts
> +	public gi?: UserGameIntegrationEntity;
An one-to-many relationship implies `gi` must be an array.

2020-08-22 10:42 UTC, favna requested changes

2020-08-22 10:42 UTC, favna commented on src/lib/orm/entities/UserGameIntegrationEntity.ts
> +	@Column({ type: 'json', name: 'extraData' })
This can be "jsonb" for a tiny performance increase https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/

2020-08-22 10:42 UTC, favna commented on src/lib/orm/migrations/1598083459734-V23_AddGIData.ts
> +					new TableColumn({ name: 'extra_data', type: 'json' })
Same here about jsonb

2020-08-22 10:44 UTC, kyranet commented on src/lib/orm/entities/UserGameIntegrationEntity.ts
> +	@Column({ type: 'json', name: 'extraData' })
Also remove the name, it's not necessary. Besides, `extraData` goes against Postgres's naming convention (fields should be lower_snake_case).

2020-08-22 12:10 UTC, kyranet requested changes

2020-08-22 12:10 UTC, kyranet commented on scripts/SetMigrations.sql
> +	(1598083459734, 'V23_AddGIData1598083459734')
```suggestion
	(1598083459734, 'V23AddGIData1598083459734')
```

And rename the file and the class.

2020-08-22 12:10 UTC, kyranet commented on src/commands/GameIntegration/brawlstars.ts
> +	flagSupport: true,
This leaked into this PR, it's out of scope.

2020-08-22 13:48 UTC, Stitch07 commented on scripts/SetMigrations.sql
> +	(1598083459734, 'V23_AddGIData1598083459734')
The class is already named that, and file names don't follow VX_Something.

2020-08-22 14:10 UTC, kyranet requested changes

2020-08-22 14:10 UTC, kyranet commented on scripts/SetMigrations.sql
> +	(1598083459734, 'V23AddGIData1598083459734')
```suggestion
	(1598083459734, 'V23AddGIData1598083459734');
```

2020-08-22 14:12 UTC, kyranet approved these changes

2020-08-22 15:08 UTC, favna approved these changes

2020-08-22 15:11 UTC, merged