fix(dehoist): question usernames as well
skyra-project/skyra pull request #1225
Opened 2020-08-21 21:11 UTC by cfanoulis

Fixes recent issue popping up in Discord

Tested, needs reviews please
Target: weekend release

2020-08-21 21:18 UTC, kyranet requested changes

2020-08-21 21:18 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
> +				const newNick = `🠷 ${displayName.slice(2)}`;
But... why remove two? If anything what you should do is:

1. Continue early if `displayName` is undefined.
1. Store `displayName.codePointAt(0)` as a constant.
1. Check if the constant is lower than `kLowestCode`.
1. If it is, check the byte range, `codePoint <= 0xFF ? 1 : 2`, assign it to a constant.
1. Call `.slice()` with the previous constant.

🎉! UTF-16 support!

2020-08-21 21:33 UTC, cfanoulis commented
I remove 2 because I use the special char + a space, for visuals

uh I guess I'll do what you did about UTF-18 tho

2020-08-21 21:38 UTC, kyranet commented
Most of the symbols used to hoist are "noisy" in a sense, e.g. `!`. For visuals, people add themselves a space. However, this is not always the case. If I set my nickname as `!kyra`, this would change it to `🠷 yra`.

2020-08-22 08:22 UTC, cfanoulis commented on src/commands/Moderation/dehoist.ts
> +				const newNick = `🠷 ${displayName.slice(2)}`;
resolved in 52b0a266b8949

2020-08-22 08:23 UTC, kyranet requested changes

2020-08-22 08:23 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
> +
```suggestion
			const displayName = memberTag.nickname ?? this.client.userTags.get(memberId)!.username;
			if (!displayName) continue;

			const char = displayName.codePointAt(0)!;
```

2020-08-22 08:23 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
>  			}
Flatten this with `if (char >= this.kLowestCode) continue;`

2020-08-22 08:27 UTC, cfanoulis commented on src/commands/Moderation/dehoist.ts
> +
resolved in f6c57c8

2020-08-22 08:27 UTC, cfanoulis commented on src/commands/Moderation/dehoist.ts
>  			}
resolved in f6c57c8

2020-08-22 08:30 UTC, kyranet requested changes

2020-08-22 08:30 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
> +			if (char > this.kLowestCode) continue;
```suggestion
			const char = displayName.codePointAt(0)!;
			if (char > this.kLowestCode) continue;

```

2020-08-22 08:30 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
> +			// Replace the first character of the offending user's with a downwards arrow, bringing'em down, down ,down
```suggestion
			// Replace the first character of the offending user's with an UTF-16 character, bringing'em down, down, down.
```

2020-08-22 08:30 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
> +			} catch (error) {
```suggestion
			} catch {
```

2020-08-22 08:30 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
> +			counter++;
```suggestion

			++counter;
```

2020-08-22 08:33 UTC, cfanoulis commented on src/commands/Moderation/dehoist.ts
> +			counter++;
does it make a difference? we don't access the value either way, unless one is more performant or something than the other?

2020-08-22 08:34 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
> +			counter++;
More performant as it doesn't clone the value but just increases it. It's also what we do everywhere else in Skyra.
I also added one line of padding for better readability.

2020-08-22 08:37 UTC, kyranet requested changes

2020-08-22 08:37 UTC, kyranet commented on src/commands/Moderation/dehoist.ts
> +			if (!displayName) return;
```suggestion
			if (!displayName) continue;
```

2020-08-22 08:44 UTC, kyranet approved these changes

2020-08-22 08:54 UTC, closed without merging

2020-08-22 09:04 UTC, cfanoulis commented
My dumbass forgot and deleted the repo, moved to #1228