feat: queue exporting
skyra-project/skyra pull request #1229
Opened 2020-08-22 13:01 UTC by cfanoulis

Closes #852

Reviews needed (some things are not really optimal)

2020-08-22 13:19 UTC, Stitch07 requested changes

2020-08-22 13:19 UTC, Stitch07 commented on src/commands/Music/add.ts
> +		if (typeof songs === 'string') return this.client.commands.get('import')!.run(message, [songs]);
instead of this I'd recommend modifying the `song` argument, so run() accepts TrackData[] in both cases.

2020-08-22 13:19 UTC, Stitch07 commented on src/commands/Music/exportqueue.ts
> +			new MessageAttachment(Buffer.from(data), `${message.guild!.name}-${Date.now()}.squeue`)
this needs localization

2020-08-22 13:19 UTC, Stitch07 commented on src/commands/Music/importqueue.ts
> +			data = (await Promise.all(
Instead of saving URLs, consider saving [TrackData#track](https://github.com/lavacord/Lavacord/blob/83cf277/src/lib/Types.ts#L457) so we don't have to fetch info from the Lavalink node for every track

2020-08-22 13:19 UTC, Stitch07 commented on src/commands/Music/exportqueue.ts
> +		const data = JSON.stringify(message.guild!.music.queue.map((v) => v.url));
Add a limit here, 100 sounds reasonable to me.

2020-08-22 15:09 UTC, favna commented on src/commands/Music/exportqueue.ts
> +	// extendedHelp: (language) => language.get('COMMAND_EXPORT_EXTENDED'),
I mean, obviously need re-enabling

2020-08-22 15:09 UTC, favna commented on src/commands/Music/importqueue.ts
> +	// extendedHelp: (language) => language.get('COMMAND_ADD_EXTENDED'),
![](https://play.pokemonshowdown.com/sprites/ani/ditto.gif)

2020-08-22 15:10 UTC, favna commented on src/commands/Music/importqueue.ts
> +		//
```suggestion
```

🧹

2020-08-23 03:51 UTC, Stitch07 requested changes

2020-08-23 03:51 UTC, Stitch07 commented on src/commands/Music/importqueue.ts
> +		if (message.attachments.size === 0 && !url) throw `I need a queue to import to the decks!`;
This needs localization

2020-08-23 03:51 UTC, Stitch07 commented on src/commands/Music/importqueue.ts
> +			throw `Sorry, but I'm having issues trying to import that playlist. Are you sure it's from my own DJ deck?`;
Same as above

2020-08-23 08:15 UTC, cfanoulis commented
in usual enkiel fashion, I've fucked the branch again. I'll close & reapply the remarks in a different branch (with a new PR)

2020-08-23 08:15 UTC, closed without merging