wip: update discord.js to stable
skyra-project/skyra pull request #1264
Opened 2020-09-06 17:05 UTC by Soumil07

TODO:

* Finish klasa update: https://github.com/skyra-project/klasa/pull/1
* Actually test this version

2020-09-06 17:19 UTC, kyranet commented
Things we need to do for this to fully work:

- [ ] Update SG (the `guilds` gateway should read `client.guilds.cache` instead of `client.guilds`), fix its detection system by adding an extra condition in the ternary.
- [ ] Update Klasa for new SG and bugfixes.
- [ ] Tweak Skyra's raw events, some of them were made to override discord.js's behaviour (presenceUpdate, guildCreate), but this is not longer possible as they removed `disabledEvents`. Instead, Skyra should use discord.js's regular events where possible (userUpdate, memberUpdate...), using raw only if it is to avoid the need of state (addMessageReaction, removeMessageReaction...) (which has been reduced in the last releases).

2020-09-09 11:57 UTC, Favna requested changes

2020-09-09 11:57 UTC, Favna commented on src/commands/Giveaway/greroll.ts
> +		return message.sendMessage(content, { allowedMentions: { users: [message.author.id], roles: [] } });
Self correction: winners should be mentionable

2020-09-09 18:50 UTC, Favna commented on src/events/guildCreate.ts
> +		const { me } = guild;
@kyranet why do we have this anyway btw? Seems a bit useless considering there's only 1 usage of `guild.me` (like 29)

2020-09-09 19:20 UTC, Favna requested changes
Revert guildCreate, requesting this as a change to block merge

2020-09-09 21:08 UTC, merged