fix: donate command
skyra-project/skyra pull request #1302
Opened 2020-09-28 14:18 UTC by Soumil07

2020-09-28 20:46 UTC, Favna requested changes

2020-09-28 20:46 UTC, Favna commented on src/commands/System/donate.ts
>  			// TODO(Soumil07): Extract i18n help formatter so it's useable here
You can remove this TODO if it's fixed. It was in place here to fix donate.

2020-10-03 05:26 UTC, kyranet approved these changes

2020-10-03 07:54 UTC, Favna approved these changes

2020-10-03 07:54 UTC, merged