feat: added guild fetch queue
skyra-project/skyra pull request #1385
Opened 2020-11-19 22:01 UTC by kyranet

2020-11-19 23:37 UTC, Favna approved these changes

2020-11-20 08:36 UTC, vladfrangu approved these changes, later dismissed

2020-11-20 08:36 UTC, vladfrangu commented on src/events/guilds/rawGuildCreateMemberFetch.ts
> +	public run(data: GatewayGuildCreateDispatch['d'], id: number) {
rename id to shardID for clarification

2020-11-20 08:36 UTC, vladfrangu commented on src/events/guilds/rawGuildDeleteMemberFetch.ts
> +	public run(data: GatewayGuildDeleteDispatch['d'], id: number) {
^

2020-11-20 11:13 UTC, Favna requested changes

2020-11-20 11:13 UTC, Favna commented on src/events/guilds/rawGuildCreateMemberFetch.ts
> +		this.client.guildMemberFetchQueue.add(id, data.id);
```suggestion
	public run(data: GatewayGuildCreateDispatch['d'], shardID: number) {
		this.client.guildMemberFetchQueue.add(shardID, data.id);
```

2020-11-20 11:13 UTC, Favna commented on src/events/guilds/rawGuildDeleteMemberFetch.ts
> +		this.client.guildMemberFetchQueue.remove(id, data.id);
```suggestion
	public run(data: GatewayGuildDeleteDispatch['d'], shardID: number) {
		this.client.guildMemberFetchQueue.remove(shardID, data.id);
```

2020-11-20 11:15 UTC, vladfrangu approved these changes

2020-11-20 11:40 UTC, merged