fix(gsearch): properly parse URL for images
skyra-project/skyra pull request #1481
Opened 2021-01-14 21:00 UTC by Favna

2021-01-14 21:02 UTC, vladfrangu submitted a review, later dismissed

2021-01-14 21:09 UTC, kyranet requested changes

2021-01-14 21:09 UTC, kyranet commented on src/commands/Google/gsearch.ts
> +				);
This should be a method, or if you want to extend https://github.com/skyra-project/skyra/blob/main/src/lib/util/iterator.ts:

```typescript
const imageUrl = first(map((item.pagemap?.cse_image ?? []).values(), (image) => parseURL(image.src)), (url) => url !== null && IMAGE_EXTENSION.test(url.pathname));
```

*If only the pipeline operator was there...*

```typescript
const imageUrl = (item.pagemap?.cse_image ?? []).values()
	|> (_) => map(_, (image) => parseURL(image.src))
	|> (_) => first(_, (url) => url !== null && IMAGE_EXTENSION.test(url.pathname);
```

Nevertheless, the cleanest and most efficient way:

```typescript
// In a method
for (const image of item.pagemap?.cse_image ?? []) {
	const url = parseURL(image.src);
	if (url && IMAGE_EXTENSION.test(url.pathname)) return url.href;
}
```

2021-01-14 21:12 UTC, kyranet requested changes
Your unit tests also failed.

2021-01-15 08:10 UTC, kyranet approved these changes
Goole lol

2021-01-15 08:10 UTC, merged