New Crowdin updates
skyra-project/skyra pull request #1554
Opened 2021-02-15 10:41 UTC by NM-EEA-Y

2021-02-15 11:33 UTC, kyranet commented
@Favna can you resync please? This PR is invalid.

2021-02-15 20:22 UTC, Favna submitted a review, later dismissed

2021-02-16 18:18 UTC, Favna requested changes

2021-02-16 18:18 UTC, Favna commented on src/languages/ru-RU/giveaway.json
> +	"endedPlural": "Победители: {{winners, andList}}",
```suggestion
	"ended_plural": "Победители: {{winners, andList}}",
```

2021-02-16 19:04 UTC, Favna approved these changes

2021-02-16 19:04 UTC, merged