refactor: move everything audio to its own folder
skyra-project/skyra pull request #1564
Opened 2021-02-16 23:31 UTC by kyranet

2021-02-17 07:02 UTC, vladfrangu requested changes

2021-02-17 07:02 UTC, vladfrangu commented on src/audio/lib/websocket/WebsocketHandler.ts
> +import { CloseCodes, WebsocketEvents } from './Shared';
WebSocket

2021-02-18 18:24 UTC, Favna requested changes

2021-02-18 18:24 UTC, Favna commented on src/audio/lib/queue/QueueStore.ts
> +				lua: readFileSync(resolve(rootFolder, 'scripts', 'audio', `${command.name}.lua`)).toString()
Remove `"postbuild": "node scripts/copy-lua-files.mjs",` from `package.json`, as well as the script then.

2021-02-18 22:45 UTC, Favna approved these changes

2021-02-18 22:46 UTC, vladfrangu approved these changes

2021-02-18 23:14 UTC, merged