feat: added Skyra.Database scaffold
skyra-project/skyra pull request #1567
Opened 2021-02-17 22:33 UTC by kyranet

2021-02-17 22:36 UTC, Tylertron1998 reviewed
wasn't there the idea of moving all services into a /services folder, to avoid cluttering up everything with .sln and what not?

2021-02-18 18:16 UTC, Favna requested changes
Also will we be moving the bot stuff to its own folder in this PR? If yes please do it at the very very end and once the PR has been approved by reviewers. Otherwise, a PR right after this one.

2021-02-18 18:16 UTC, Favna commented on .github/workflows/continuous-integration.yml
> +          dotnet test services/Skyra.Tests
```suggestion
        run: dotnet test services/Skyra.Tests
```

Please don't do this. You only need a pipe for multi-line scripts.

2021-02-18 18:16 UTC, Favna commented on .github/workflows/continuous-integration.yml
> +          dotnet build services
```suggestion
        run: dotnet build services
```

2021-02-18 18:35 UTC, Tylertron1998 commented
> Also will we be moving the bot stuff to its own folder in this PR? If yes please do it at the very very end and once the PR has been approved by reviewers. Otherwise, a PR right after this one.

I'm happy for moving the bot over into it's own repo - would make everything a *lot* cleaner imo. But might be a little more suitable in it's own PR? As I imagine a lot of pathing in commands and stuff (image commands for example) will need to be changed.

2021-02-18 19:13 UTC, Favna commented
@Tylertron1998 Not its own repo. Heck if anything goes in another repo it would be this, not the bot. This is and will always be the bot's repo. No instead it would go into it's own folder.

I meant something like this:

```
\skyra
├── crowdin.yml
├── docker
|  ├── control.ps1
|  ├── docker-compose.yml
|  └── README.md
├── LICENSE
├── README.md
├── services
|  ├── Directory.Build.props
|  ├── Skyra.Database
|  ├── Skyra.sln
|  ├── Skyra.sln.DotSettings
|  └── Skyra.Tests
└── skyra
   ├── assets
   ├── jest.config.ts
   ├── ormconfig.js
   ├── package.json
   ├── pm2.ecosystem.yml
   ├── scripts
   ├── src
   ├── tests
   ├── tsconfig.base.json
   ├── tsconfig.eslint.json
   └── yarn.lock

directory: 9 file: 16
```

2021-02-18 19:14 UTC, kyranet commented
Yes, `skyra/skyra`.

2021-02-18 19:16 UTC, Favna commented
@kyranet `skyra/bot` seems derp as well lol... I have no idea what else we can do.

2021-02-18 19:18 UTC, kyranet commented
`skyra/main`, `skyra/worker`, `skyra/services/Skyra.Main`, pick your weapon.

2021-02-18 19:19 UTC, Tylertron1998 commented
whoops, I meant in it's own folder, lol

2021-02-18 19:49 UTC, Tylertron1998 commented
`skyra/bot`? because.. you know.. it's where the 'bot' part of skyra is? :P

2021-02-18 20:01 UTC, Stitch07 commented
+1 for skyra/bot

2021-02-18 22:40 UTC, Tylertron1998 commented
> @Tylertron1998 Not its own repo. Heck if anything goes in another repo it would be this, not the bot. This is and will always be the bot's repo. No instead it would go into it's own folder.
> 
> I meant something like this:
> 
> ```
> \skyra
> ├── crowdin.yml
> ├── docker
> |  ├── control.ps1
> |  ├── docker-compose.yml
> |  └── README.md
> ├── LICENSE
> ├── README.md
> ├── services
> |  ├── Directory.Build.props
> |  ├── Skyra.Database
> |  ├── Skyra.sln
> |  ├── Skyra.sln.DotSettings
> |  └── Skyra.Tests
> └── skyra
>    ├── assets
>    ├── jest.config.ts
>    ├── ormconfig.js
>    ├── package.json
>    ├── pm2.ecosystem.yml
>    ├── scripts
>    ├── src
>    ├── tests
>    ├── tsconfig.base.json
>    ├── tsconfig.eslint.json
>    └── yarn.lock
> 
> directory: 9 file: 16
> ```
> 
> ![image](https://user-images.githubusercontent.com/4019718/108408862-dbaf7e80-7225-11eb-86cd-2cb586f5998e.png)

scratch that, this looks perfect, favna 4 the win

2021-02-20 13:39 UTC, closed without merging