feat: add unit tests
skyra-project/skyra pull request #1585
Opened 2021-02-21 14:01 UTC by Tylertron1998

This adds in unit tests for Skyra.Database - and should serve as a good base for people to write tests on.
Skyra.Grpc isn't tested here, as that'll require integration tests, which is a whole other PR.

2021-02-21 18:24 UTC, kyranet approved these changes, later dismissed

2021-02-22 01:07 UTC, kyranet approved these changes, later dismissed

2021-02-22 08:16 UTC, Stitch07 requested changes

2021-02-22 08:16 UTC, Stitch07 commented on services/Skyra.Tests/UnitTests/Database/Stubs/TestDbContext.cs
> +		public DbSet<UserStub> Users { get; set; }
Think you need a `#nullable disable` in this file

2021-02-22 10:23 UTC, kyranet submitted a review, later dismissed

2021-02-22 19:29 UTC, Tylertron1998 commented
codecov seems to be broken at the moment, so here is the coverage reported inside of rider:
![image](https://user-images.githubusercontent.com/34944514/108759408-3574b900-7544-11eb-8312-48ebb4c44879.png)

2021-02-22 19:30 UTC, Tylertron1998 commented on .github/workflows/continuous-integration.yml
> +          POSTGRES_NAME: test
note; while I can pass `-e POSTGRES_NAME=test` to `docker container run`, I would have to pass the *entire* connection string to `dotnet tool run dotnet-ef database update` - which is not ideal.

2021-03-03 00:02 UTC, Favna approved these changes

2021-03-03 00:03 UTC, kyranet approved these changes

2021-03-03 00:03 UTC, merged