Quick first section README re-write
skyra-project/skyra pull request #1652
Opened 2021-03-17 22:02 UTC by Darqam

A quick re-write of the "A note to aspiring developers who want to self host Skyra" subsection. Written in a bit more neutral tone as opposed to opinionated. Removed links to the 2 VPS but could be added back if there was a good reason to have them.

2021-03-17 22:15 UTC, kyranet submitted a review, later dismissed

2021-03-18 00:08 UTC, Favna requested changes

2021-03-18 00:08 UTC, Favna commented on README.md
> +The developer team does not support the idea of other self-hosted instances of Skyra. The team prides itself on providing the best experience and support for the end-users. As such, an offshoot or un
```suggestion
The developer team does not support the idea of other self-hosted instances of Skyra. The team prides itself on providing the best experience and support for the end-users. As such, an offshoot or unaffiliated mirror of Skyra may cause ill effects to the reputation and image of Skyra. If you wish to see new features implemented, please refer to the developing guidelines linked above.
```

typo

2021-03-18 08:52 UTC, kyranet approved these changes

2021-03-18 09:48 UTC, Favna approved these changes

2021-03-18 09:50 UTC, merged