Jackpot and age filter
skyra-project/skyra pull request #17
Opened 2018-11-09 09:40 UTC by Tylertron1998

Adds the jackpot command

2018-11-09 10:03 UTC, kyranet requested changes

2018-11-09 10:03 UTC, kyranet commented on src/commands/Social/jackpot.js
> +		if (message.author.settings.money < amount) return message.sendlocale('COMMAND_SLOTMACHINES_MONEY', [message.author.settings.money]);
The language key `COMMAND_SLOTMACHINES_MONEY` should be renamed to `SOCIAL_MISSING_MONEY`. Change other languages aswell and move with the other `SOCIAL_*` keys.

2018-11-09 10:03 UTC, kyranet commented on src/commands/Social/jackpot.js
> +			const userResolved = await this.client.users.fetch(jackpotUser.id);
It does not return null, it throws. `.catch(() => null)` can be used instead.
However, in Skyra we use another system: `this.client.fetchTag(id);`.

2018-11-09 10:03 UTC, kyranet commented on src/commands/Social/jackpot.js
> +			if (userResolved === null) return `Deleted user: ${jackpotUser.amount}`;
Use ternary instead.

2018-11-09 10:03 UTC, kyranet commented on src/commands/Social/jackpot.js
> +		return message.sendLocale('COMMAND_JACKPOT_USER_LIST', [users, this.client.jackpot.users.reduce((a, b) => { a.amount += b.amount; })]);
This is not how Array#reduce works, the first argument of the callback is the last value returned from the callback, and it should define the first value as 0:

```suggestion
		return message.sendLocale('COMMAND_JACKPOT_USER_LIST', [users, this.client.jackpot.users.reduce((a, b) => a + b.amount, 0)]);
```

2018-11-09 10:03 UTC, kyranet commented on src/lib/Skyra.js
> +
Remove this new line

2018-11-09 10:03 UTC, kyranet commented on src/lib/Skyra.js
> +		 * @since 3.0.0
We're in Skyra 4.0.0 Nerom, 3.0.0 is Royal.

2018-11-09 10:03 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		if (await this.client.providers.default.has('jackpot', id)) await this.client.providers.default.update('jackpot', id, { amount });
Since this is now client-wide (remember I misunderstood before), it should be in clientStorage.

2018-11-09 10:03 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		return this.users.find(jackpotUser => jackpotUser.id === id).amount;
This essentially `return amount;`.

2018-11-09 10:03 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		for (const user of this.users) {
Once you move this to clientStorage, it'll be as easy as doing:

```javascript
this.client.settings.reset('jackpot');
```

2018-11-09 10:03 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +        const amount = this.users.reduce((a, b) => { a.amount += b.amount; });
```suggestion
        const amount = this.users.reduce((a, b) => a + b.amount, 0);
```

2018-11-09 10:03 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		this.users = [];
Again, once done in clientStorage, `this.users` will be unnecessary.

2018-11-09 10:03 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		this.time = 0;
Not define in the constructor, what is this for?

2018-11-09 10:03 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		this.data = await this.client.providers.default.getAll('jackpot');
Again, once done in clientStorage, this can go. And this.data is not defined in the constructor.

2018-11-09 10:03 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		if (this.users.length === 0) return null;
```suggestion
		if (this.users.length === 0) return { id: null, amount: 0 };
```

And make the task always deconstruct draw's output, just check if id is null.

2018-11-12 10:08 UTC, kyranet requested changes

2018-11-12 10:08 UTC, kyranet commented on src/commands/Social/jackpot.js
> +		if (!this.client.settings.jackpot.some(user => user.id === message.author.id)) return message.sendLocale('COMMAND_JACKPOT_USER_NOT_FOUND');
Make this automatically join instead of making them join.

2018-11-12 10:08 UTC, kyranet commented on src/events/onceReady.js
> +		if (!this.client.schedule.tasks.some(task => task.taskName === 'jackpot')) await this.client.schedule.create('jackpot', '@daily');
Wrong event, should be in klasaReady: https://github.com/kyranet/Skyra/blob/master/src/events/klasaReady.js

2018-11-12 10:08 UTC, kyranet commented on src/languages/en-US.js
> +			COMMAND_JACKPOT_USER_WIN: (amount) => `Congrats! You've won ${amount} in the jackpot!`,
Missing Shiny

2018-11-12 10:08 UTC, kyranet commented on src/languages/en-US.js
> +			COMMAND_JACKPOT_USER_LIST: (users, amount) => `The current users have joined the jackpot: \n${users.join('\n')}\n\n CURRENT JACKPOT WORTH: ${amount}.`,
Missing Shiny

2018-11-12 10:08 UTC, kyranet commented on src/languages/en-US.js
> +			COMMAND_JACKPOT_USER_JOIN: (amount) => `You have now joined the jackpot, with a starting bet of ${amount}. I will draw a winner at midnight and if you have won, I will DM you!`,
Missing Shiny

2018-11-12 10:08 UTC, kyranet commented on src/lib/Skyra.js
> +
Remove empty line

2018-11-12 10:08 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		console.log(object);
👀

2018-11-12 10:08 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		const object = this.client.settings.jackpot.find(user => user.id === id);
Find the index first, object will be `this.client.settings.jackpot[index];`. Also, check existence first.

2018-11-12 10:08 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		} else await this.client.settings.update('jackpot', { id, amount });
```javascript
if (object)
	await thing;
else
	await otherThing;
```

2018-11-12 10:08 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +        const amount = this.client.settings.jackpot.reduce((a, b) => a + b.amount, 0);
The indentation in this line is odd

2018-11-12 12:05 UTC, kyranet requested changes

2018-11-12 12:05 UTC, kyranet commented on src/commands/Social/jackpot.js
> +		// eslint-disable-next-line
Don't disable all rules, if you need to disable one, specify which

2018-11-12 12:05 UTC, kyranet commented on src/languages/en-US.js
> +				renmider: 'The jackpot is drawn once a day. You will only know if you win - however you can view all users in the jackpot by using @Skyra jackpot view.'
reminder

2018-11-12 12:05 UTC, kyranet commented on src/languages/en-US.js
> +				renmider: 'The jackpot is drawn once a day. You will only know if you win - however you can view all users in the jackpot by using @Skyra jackpot view.'
Add an inline code to the command to stand out

2018-11-12 12:05 UTC, kyranet commented on src/languages/en-US.js
> +			COMMAND_JACKPOT_USER_ALREADY_JOINED: (user) => `Sorry, dear ${user.username}, but you have already joined the jackpot. You can increase your bet with @Skyra jackpot add <amount>.`,
Same here

2018-11-12 12:05 UTC, kyranet commented on src/languages/en-US.js
> +			COMMAND_JACKPOT_NOT_FOUND: 'Sorry, there is no jackpot at the moment. You can start one with @Skyra jackpot join though!',
Same here

2018-11-12 12:05 UTC, kyranet commented on src/languages/en-US.js
> +			COMMAND_JACKPOT_USER_JOIN: (amount) => `You have now joined the jackpot, with a starting bet of ${amount}${SHINY}. I will draw a winner at midnight and if you have won, I will DM you!`,
I will notify you in direct messages

2018-11-12 12:05 UTC, kyranet commented on src/languages/en-US.js
> +			COMMAND_JACKPOT_USER_LIST: (users, amount) => `The current users have joined the jackpot: \n${users.join('\n')}\n\n CURRENT JACKPOT WORTH: ${amount}${SHINY}.`,
What if there's only one user?

2018-11-14 18:52 UTC, vladfrangu requested changes

2018-11-14 18:52 UTC, vladfrangu commented on src/commands/Social/jackpot.js
> +		for (const user of this.client.settings.jackpot) {
Should use Promise.all
```js
const users = await Promise.all(
	this.client.settings.jackpot.map(
		(user) => this.client.fetchTag(user.id).then((tag) => `${tag}: ${user.amount}${SHINY}`).catch(() => `Deleted User: ${user.amount}${SHINY}`)
	)
);
```

2018-11-14 18:52 UTC, vladfrangu commented on src/languages/en-US.js
> +			COMMAND_JACKPOT_USER_LIST: (users, amount) => `There ${users.length > 1 ? `are ${users.length} users` : `is one user`} in the jackpot currently: \n${users.join('\n')}\n\n CURRENT JACKPOT WORTH: ${
That space after the two new lines before `Current Jackpot Worth`. Also, that caps use tho..

2018-11-14 18:52 UTC, vladfrangu commented on src/languages/en-US.js
> +
nit: Useless new line?

2018-11-14 18:52 UTC, vladfrangu commented on src/lib/util/Games/Jackpot.js
> +		const index = this.client.settings.jackpot.findIndex(user => user.id === id);
This should use find with indexOf imho, to reduce the double find at the bottom.

Otherwise, move the returns in the if check, remove the else check and voila

2018-11-14 18:56 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		const index = this.client.settings.jackpot.findIndex(user => user.id === id);
Actually, it should be kept.

2018-11-14 18:59 UTC, kyranet commented on src/lib/util/Games/Jackpot.js
> +		const index = this.client.settings.jackpot.findIndex(user => user.id === id);
```javascript
const element = { id, amount: index === -1 ? amount : this.client.settings.jackpot[index].amount + amount };
await this.client.settings.update('jackpot', element, { arrayPosition: index === -1 ? null : index });
return element;
```

action: 'overwrite' is unneeded as it's not passing an array, in fact, it nukes all other entries.

2019-02-12 22:27 UTC, closed without merging