chore: updated dependencies, updated a few things
skyra-project/skyra pull request #2028
Opened 2021-09-11 13:50 UTC by kyranet

2021-09-11 15:17 UTC, Favna requested changes

2021-09-11 15:17 UTC, Favna commented on package.json
> +		"typeorm": "0.2.37",
huh?

2021-09-11 15:19 UTC, kyranet commented on package.json
> +		"typeorm": "0.2.37",
UHHHHHHHHHHHHHHHHHHHHHHHHHHHH

2021-09-12 10:50 UTC, Favna approved these changes

2021-09-12 10:51 UTC, merged