fix(listeners): log manual bans
skyra-project/skyra pull request #2185
Opened 2022-02-03 00:23 UTC by Nytelife26

Fixes #2184.

2022-02-03 00:30 UTC, kyranet commented
Oops, old code that we didn't catch due to the lack of strict types...

By the way, the type that's emitted is GuildBan: https://discord.js.org/#/docs/discord.js/stable/class/GuildBan

2022-02-03 18:42 UTC, favna requested changes

2022-02-03 18:42 UTC, favna commented on src/listeners/guilds/bans/guildBanAdd.ts
> +	public async run({ guild, user }: { guild: Guild; user: User }) {
Adjust the type as per Kyra's comment above and then it's good

2022-02-05 08:35 UTC, kyranet approved these changes

2022-02-05 14:48 UTC, favna approved these changes

2022-02-05 14:48 UTC, merged