feat: shifted to select menu for eval reply options
skyra-project/skyra pull request #2387
Opened 2022-10-14 13:04 UTC by KrishAgarwal2811

This PR adds a feature to the eval command. Before we used to use message-based methods to ask for the desired method of viewing content more than the discord size limit. But now we are using a message action row instead.

Here are some images on how it looks: 
![message one](https://cdn.discordapp.com/attachments/812340649276866580/1030449623141208124/unknown.png)
![message two](https://cdn.discordapp.com/attachments/812340649276866580/1030449526554771506/unknown.png)

2022-10-14 17:47 UTC, favna requested changes

2022-10-14 17:47 UTC, favna commented on src/lib/util/Parsers/ExceededLength.ts
> +					container.logger.fatal(err.message);
Remove the log, then remove the braces to directly return null again.

2022-10-14 18:04 UTC, favna approved these changes

2022-10-14 18:04 UTC, favna commented
Tested with Dragonair

2022-10-15 08:02 UTC, kyranet approved these changes

2022-10-15 08:07 UTC, merged