feat: change invite links to use Discord URLs instead
skyra-project/skyra pull request #2460
Opened 2023-05-11 17:16 UTC by enxg

This allows the users to invite the bot/join the support server without leaving the Discord client.

![image](https://github.com/skyra-project/skyra/assets/61084101/497647ec-e268-49b5-a9cf-b6260bcf9650)

2023-05-11 20:45 UTC, favna requested changes
Apply this patch:
```patch
diff --git a/src/commands/General/invite.ts b/src/commands/General/invite.ts
index c27e0b6a..eda7d446 100644
--- a/src/commands/General/invite.ts
+++ b/src/commands/General/invite.ts
@@ -1,9 +1,10 @@
 import { LanguageKeys } from '#lib/i18n/languageKeys';
 import { SkyraCommand } from '#lib/structures';
 import { BrandingColors } from '#utils/constants';
+import { hyperlink } from '@discordjs/builders';
 import { ApplyOptions } from '@sapphire/decorators';
 import { send } from '@sapphire/plugin-editable-commands';
-import { PermissionFlagsBits } from 'discord-api-types/v9';
+import { OAuth2Scopes, PermissionFlagsBits } from 'discord-api-types/v9';
 import { Message, MessageEmbed } from 'discord.js';
 import type { TFunction } from 'i18next';
 
@@ -26,22 +27,55 @@ export class UserCommand extends SkyraCommand {
 	}
 
 	private getEmbed(t: TFunction, shouldNotAddPermissions: boolean): MessageEmbed {
+		const embeddedInviteLink = hyperlink(
+			t(LanguageKeys.Commands.General.InvitePermissionInviteText),
+			this.generateInviteLink(shouldNotAddPermissions)
+		);
+		const embeddedJoinLink = hyperlink(t(LanguageKeys.Commands.General.InvitePermissionSupportServerText), 'https://discord.com/invite/6gakFR2');
+
 		return new MessageEmbed() //
 			.setColor(BrandingColors.Primary)
 			.setDescription(
 				[
-					[
-						`[${t(
-							LanguageKeys.Commands.General.InvitePermissionInviteText
-						)}](https://discord.com/oauth2/authorize?client_id=266624760782258186&permissions=${
-							shouldNotAddPermissions ? '0' : '534185897078'
-						}&scope=applications.commands%20bot)`,
-						`[${t(LanguageKeys.Commands.General.InvitePermissionSupportServerText)}](https://discord.com/invite/6gakFR2)`
-					].join(' | '),
+					[embeddedInviteLink, embeddedJoinLink].join(' | '),
 					shouldNotAddPermissions ? undefined : t(LanguageKeys.Commands.General.InvitePermissionsDescription)
 				]
 					.filter(Boolean)
 					.join('\n')
 			);
 	}
+
+	private generateInviteLink(shouldNotAddPermissions: boolean) {
+		return this.container.client.generateInvite({
+			scopes: [OAuth2Scopes.ApplicationsCommands, OAuth2Scopes.Bot],
+			permissions: shouldNotAddPermissions
+				? []
+				: [
+						PermissionFlagsBits.AddReactions,
+						PermissionFlagsBits.AttachFiles,
+						PermissionFlagsBits.BanMembers,
+						PermissionFlagsBits.ChangeNickname,
+						PermissionFlagsBits.CreatePrivateThreads,
+						PermissionFlagsBits.CreatePublicThreads,
+						PermissionFlagsBits.DeafenMembers,
+						PermissionFlagsBits.EmbedLinks,
+						PermissionFlagsBits.KickMembers,
+						PermissionFlagsBits.ManageChannels,
+						PermissionFlagsBits.ManageEmojisAndStickers,
+						PermissionFlagsBits.ManageGuild,
+						PermissionFlagsBits.ManageMessages,
+						PermissionFlagsBits.ManageNicknames,
+						PermissionFlagsBits.ManageRoles,
+						PermissionFlagsBits.ManageThreads,
+						PermissionFlagsBits.MoveMembers,
+						PermissionFlagsBits.MuteMembers,
+						PermissionFlagsBits.ReadMessageHistory,
+						PermissionFlagsBits.SendMessages,
+						PermissionFlagsBits.SendMessagesInThreads,
+						PermissionFlagsBits.UseExternalEmojis,
+						PermissionFlagsBits.UseExternalStickers,
+						PermissionFlagsBits.ViewChannel
+				  ]
+		});
+	}
 }
```

2023-05-11 23:19 UTC, favna submitted a review, later dismissed

2023-05-12 15:07 UTC, kyranet requested changes
The array is inefficient when we can just OR the bits ourselves.

2023-05-12 15:07 UTC, kyranet commented on src/commands/General/invite.ts
> +				  ]
```suggestion
				? 0n
				: PermissionFlagsBits.AddReactions |
				  PermissionFlagsBits.AttachFiles |
				  PermissionFlagsBits.BanMembers |
				  PermissionFlagsBits.ChangeNickname |
				  PermissionFlagsBits.CreatePrivateThreads |
				  PermissionFlagsBits.CreatePublicThreads |
				  PermissionFlagsBits.DeafenMembers |
				  PermissionFlagsBits.EmbedLinks |
				  PermissionFlagsBits.KickMembers |
				  PermissionFlagsBits.ManageChannels |
				  PermissionFlagsBits.ManageEmojisAndStickers |
				  PermissionFlagsBits.ManageGuild |
				  PermissionFlagsBits.ManageMessages |
				  PermissionFlagsBits.ManageNicknames |
				  PermissionFlagsBits.ManageRoles |
				  PermissionFlagsBits.ManageThreads |
				  PermissionFlagsBits.MoveMembers |
				  PermissionFlagsBits.MuteMembers |
				  PermissionFlagsBits.ReadMessageHistory |
				  PermissionFlagsBits.SendMessages |
				  PermissionFlagsBits.SendMessagesInThreads |
				  PermissionFlagsBits.UseExternalEmojis |
				  PermissionFlagsBits.UseExternalStickers |
				  PermissionFlagsBits.ViewChannel
```

2023-05-12 16:36 UTC, kyranet approved these changes

2023-05-12 18:28 UTC, merged