feat: remove animal commands
skyra-project/skyra pull request #2557
Opened 2024-01-26 23:43 UTC by OfficialSirH

https://github.com/skyra-project/artiel/pull/109

2024-01-26 23:52 UTC, favna requested changes
You forgot to delete the en-US JSON file

2024-01-27 08:49 UTC, kyranet approved these changes

2024-01-27 09:26 UTC, favna approved these changes, later dismissed

2024-01-27 21:14 UTC, kyranet requested changes
The command names and aliases should be added to the v7-artiel list.

2024-01-27 22:10 UTC, kyranet requested changes
As mentioned in SDS, this needs Artiel to be released so the command IDs are available.

2024-01-28 12:52 UTC, kyranet approved these changes

2024-01-28 12:52 UTC, merged