feat: remove love, pop, rate
skyra-project/skyra pull request #2615
Opened 2024-04-07 22:22 UTC by OfficialSirH

Completes https://github.com/skyra-project/artiel/pull/133

2024-04-08 07:20 UTC, kyranet requested changes
You have to delete the strings from `en-US/commands/fun.json` too

2024-04-08 15:04 UTC, kyranet approved these changes
Sneaky `escaperopeOutput`, thankfully you noticed that in between, because I would have probably deleted it with the rest LOL

2024-04-10 17:46 UTC, favna approved these changes

2024-04-11 20:00 UTC, kyranet approved these changes

2024-04-11 20:00 UTC, merged