fix: use discord.js-utilities functions
skyra-project/skyra pull request #2631
Opened 2024-06-03 23:30 UTC by favna

2024-06-15 21:58 UTC, kyranet requested changes

2024-06-15 21:58 UTC, kyranet commented on docker-compose.yml
> -    container_name: postgres
What is this change?

2024-06-16 02:24 UTC, favna commented on docker-compose.yml
> +    container_name: postgres2
```suggestion
    container_name: postgres
```

2024-06-16 02:24 UTC, favna commented on docker-compose.yml
> +      - postgres2
```suggestion
      - postgres
```

2024-06-16 02:24 UTC, favna commented on docker-compose.yml
> -    container_name: postgres
Something I pushed accidentally

2024-06-16 07:41 UTC, kyranet approved these changes

2024-06-16 07:41 UTC, merged