Change help command to show the --all flag text in the content, and get it from the language
skyra-project/skyra pull request #396
Opened 2019-10-22 20:36 UTC by tech6hutch

![image](https://user-images.githubusercontent.com/25398066/67330168-fa92e900-f4e9-11e9-9762-6b760d02e09b.png)

Tested working.

A _better_ solution for #322

2019-10-22 20:40 UTC, tech6hutch commented
Spanish works too: ![image](https://user-images.githubusercontent.com/25398066/67330601-991f4a00-f4ea-11e9-893d-9b7bc2aab397.png)

2019-10-22 20:41 UTC, kyranet requested changes

2019-10-22 20:41 UTC, kyranet commented on src/commands/General/Chat Bot Info/help.ts
> +			const response = await message.send(
nit:
```suggestion
			const response = await message.sendMessage(
```

2019-10-23 10:57 UTC, kyranet approved these changes

2019-10-23 11:20 UTC, merged