fix(igdb): fixes for potentially undefined fields
skyra-project/skyra pull request #555
Opened 2019-11-18 22:15 UTC by Favna

Fixes #545

---

- Added typings from @igdb/types except in External coz their typing were incorrect causing build errors (missing the `| undefined` in `ApiObjectProperty`)
- Added a whole bunch of error handling and empty-field handling as coming the new typings show that this was needed
- Fixed the reported bug with "Guilty Gear" by ensuring company names are always returned

2019-11-18 22:17 UTC, PyroTechniac requested changes
All the enums should be made constant, unless the license is preventing that

2019-11-18 22:27 UTC, PyroTechniac submitted a review, later dismissed

2019-11-19 01:57 UTC, PyroTechniac approved these changes

2019-11-19 14:44 UTC, kyranet approved these changes

2019-11-19 14:44 UTC, merged

2019-11-23 05:04 UTC, rogersachan commented
@Favna there was a new release for the types today that might have fixed your issue: https://github.com/igdb/igdb-typescript-types

2019-11-23 08:14 UTC, Favna commented
@rogersachan thanks for the heads up. Undoubtedly that's the case as the update is based on a PR I made to the repo 😉.