security: ensure inaccessible channels cannot be quoted
skyra-project/skyra pull request #618
Opened 2019-12-04 08:11 UTC by Favna

2019-12-05 23:41 UTC, kyranet commented
Not even admins should be able to give channels Skyra or the author cannot read, so indeed, the argument itself should take care of that, as well as ensuring the channel's guild is the message's guild.

2019-12-07 00:31 UTC, kyranet requested changes

2019-12-07 00:31 UTC, kyranet commented on src/commands/System/echo.ts
> +			usage: '[channel:channelname] [message:string] [...]',
Nit: `channelname` can conflict with `string` here. Replace it with any of the following:

```suggestion
			usage: '[channel:channelname{2}] [message:string] [...]',
```

```suggestion
			usage: '[channel:channel] [message:string] [...]',
```

2019-12-07 01:28 UTC, Favna commented
Merged one of em but I recommend you test it with SkyraDev before pushing to production because I'm not sure if my own tests were proper.

2019-12-07 09:59 UTC, kyranet approved these changes

2019-12-07 10:02 UTC, merged