feat: ship command
skyra-project/skyra pull request #792
Opened 2020-01-25 23:01 UTC by Favna

Ship command, ported from Ribbon

<details> <summary> screenshots inside </summary>

![image](https://user-images.githubusercontent.com/4019718/73128374-e66df480-3fce-11ea-9cc2-2841e06e6ea6.png)
![image](https://user-images.githubusercontent.com/4019718/73128376-e968e500-3fce-11ea-9188-74c024b3a3d1.png)
![image](https://user-images.githubusercontent.com/4019718/73128378-ec63d580-3fce-11ea-9d69-93bcba5033cd.png)

</details>

2020-01-26 10:15 UTC, vladfrangu requested changes

2020-01-26 10:15 UTC, vladfrangu commented on src/commands/Misc/ship.ts
> +			if (!arg) return message.guild?.members.random()!.user;
Won't this `?.` generate code that is..useless? We'll always have message.guild in this context

2020-01-26 10:15 UTC, vladfrangu commented on src/commands/Misc/ship.ts
> +			if (!arg) return message.guild?.members.random()!.user;
Ditto

2020-01-26 10:15 UTC, vladfrangu commented on src/commands/Misc/ship.ts
> +			.addImage(darkTheme ? this.darkThemeTemplate! : this.lightThemeTemplate!, 0, 0, 224, 88)
You could simplify this by removing the `!` from the end, and where you define the buffers:
```ts
private darkThemeTemplate!: Buffer;
```

2020-01-26 11:48 UTC, vladfrangu submitted a review, later dismissed

2020-01-28 21:54 UTC, kyranet requested changes

2020-01-28 21:54 UTC, kyranet commented on src/commands/Misc/ship.ts
> +	private removeSymbolsRegex = /(?:[~`!@#%^&*(){}[\];:"'<,.>?/\\|_+=-])+/g;
```suggestion
	private readonly kRemoveSymbolsRegex = /(?:[~`!@#%^&*(){}[\];:"'<,.>?/\\|_+=-])+/g;
```

And update all references

2020-01-28 22:20 UTC, kyranet approved these changes

2020-01-28 22:23 UTC, merged