feat(Webhooks): added webhook for Bots For Discord
skyra-project/skyra pull request #963
Opened 2020-05-04 23:20 UTC by kyranet

I missed this when migrating the API from Ny-API to Skyra in 5.1.0, but fear not, it's back again!

2020-05-04 23:22 UTC, favna approved these changes

2020-05-04 23:23 UTC, favna requested changes
On second thought, `@ApplyOptions` should work I think. Route extends Piece.

2020-05-04 23:24 UTC, Favna commented on src/routes/webhooks/b4d.ts
> +	}
```suggestion
import ApiRequest from '@lib/structures/api/ApiRequest';
import ApiResponse from '@lib/structures/api/ApiResponse';
import { ApplyOptions } from '@skyra/decorators';
import { Route, RouteOptions } from 'klasa-dashboard-hooks';
import { TOKENS } from '@root/config';
import { UserSettings } from '@lib/types/settings/UserSettings';

@ApplyOptions<RouteOptions>({ route: 'webhooks/b4d' })
export default class extends Route {

```

2020-05-04 23:53 UTC, kyranet commented on src/routes/webhooks/b4d.ts
> +	}
Fixed in d992a73.

2020-05-05 00:09 UTC, favna approved these changes

2020-05-05 00:16 UTC, merged