build(dev-deps): bump dev dependencies
skyra-project/skyra pull request #969
Opened 2020-05-05 18:30 UTC by Favna

2020-05-07 19:53 UTC, Favna commented
There are many many linting errors left. Any help is much welcome!

2020-05-21 17:18 UTC, kyranet requested changes

2020-05-21 17:18 UTC, kyranet commented on src/commands/Tools/quote.ts
> +		if (/^(beta\.|canary\.)?discord(?:app)?\.com$/g.test(parsed.hostname)) return null;
```suggestion
		if (/^(ptb\.|canary\.)?discord(?:app)?\.com$/g.test(parsed.hostname)) return null;
```

2020-05-21 21:16 UTC, kyranet approved these changes

2020-05-21 21:16 UTC, merged